eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

cutomerservice:
  url: http://localhost:8070/
monolith:
  url: http://localhost:8080/
orderservice:
  url: http://localhost:8090/
server:
  port: 0
spring:
  jpa:
    open-in-view: false
